-- 找不到Department的
insert into Staff (Name) values ('Royman');
insert into Staff (Name) values ('Jim');
insert into Staff (Name) values ('James');
insert into Staff (Name) values ('Alan');
insert into Staff (Name) values ('Kiah');
insert into Staff (Name) values ('Gus');
insert into Staff (Name) values ('Lynn');
insert into Staff (Name) values ('Colin');
insert into Staff (Name) values ('Gus');
insert into Staff (Name) values ('Kelvin');


-- WWW
insert into Staff (Name ,Department) values ('Eric.D.Lin' ,'WWW');	
insert into Staff (Name ,Department) values ('Barry.S.Jiang' ,'WWW');	
insert into Staff (Name ,Department) values ('Payne.Z.Pei' ,'WWW');	
insert into Staff (Name ,Department) values ('Dennis.Y.Liu' ,'WWW');	
insert into Staff (Name ,Department) values ('Fiona.Z.Cai' ,'WWW');	
insert into Staff (Name ,Department) values ('Gavin.H.Gu' ,'WWW');	
insert into Staff (Name ,Department) values ('Grace.S.Li' ,'WWW');	
insert into Staff (Name ,Department) values ('Yiga.Y.Yang' ,'WWW');	
insert into Staff (Name ,Department) values ('Louis.R.Shen' ,'WWW');	
insert into Staff (Name ,Department) values ('Zeed.W.Zhao' ,'WWW');	

-- Search
insert into Staff (Name ,Department) values ('Json.J.Hu' ,'Search');	
insert into Staff (Name ,Department) values ('Lyn.J.Zhang' ,'Search');	
insert into Staff (Name ,Department) values ('James.Y.Li' ,'Search');	
insert into Staff (Name ,Department) values ('Jack.Z.Tang' ,'Search');	
insert into Staff (Name ,Department) values ('Kevin.K.Luo' ,'Search');	
insert into Staff (Name ,Department) values ('Jack.C.Ni' ,'Search');	

-- BigData
insert into Staff (Name ,Department) values ('Joey.Y.Hou' ,'BigData');	
insert into Staff (Name ,Department) values ('Jenkin.Z.Chen' ,'BigData');	
insert into Staff (Name ,Department) values ('Jessica.J.Wang' ,'BigData');	
insert into Staff (Name ,Department) values ('Tao.Y.Chen' ,'BigData');	


-- SSL
insert into Staff (Name ,Department) values ('Amanda.J.Wu' ,'SSL');	
insert into Staff (Name ,Department) values ('Jefe.Y.Zhang' ,'SSL');	
insert into Staff (Name ,Department) values ('Kevin.R.Huang' ,'SSL');	
insert into Staff (Name ,Department) values ('Lily.H.Chen' ,'SSL');	
insert into Staff (Name ,Department) values ('Leo.H.Song' ,'SSL');	
insert into Staff (Name ,Department) values ('Randolph.Y.Sun' ,'SSL');	
insert into Staff (Name ,Department) values ('Tom.L.Huang' ,'SSL');	
insert into Staff (Name ,Department) values ('Felix.F.Zhang' ,'SSL');	
insert into Staff (Name ,Department) values ('Honor.R.Zhang' ,'SSL');	
insert into Staff (Name ,Department) values ('Jerry.Q.Tong' ,'SSL');

-- Architect
insert into Staff (Name ,Department) values ('Feng.H.Di' ,'Architect');

-- WWW&BigData Tester
insert into Staff (Name ,Department) values ('Ellen.Y.Xue' ,'WWW&BigData Tester');
insert into Staff (Name ,Department) values ('Amy.J.Shi' ,'WWW&BigData Tester');
insert into Staff (Name ,Department) values ('Arthas.J.Gong' ,'WWW&BigData Tester');
insert into Staff (Name ,Department) values ('Bernie.J.Gu' ,'WWW&BigData Tester');
insert into Staff (Name ,Department) values ('Carol.C.Li' ,'WWW&BigData Tester');
insert into Staff (Name ,Department) values ('Cherry.B.Ma' ,'WWW&BigData Tester');
insert into Staff (Name ,Department) values ('Lareina.L.Liu' ,'WWW&BigData Tester');	
insert into Staff (Name ,Department) values ('Sunny.Q.Lv' ,'WWW&BigData Tester');
insert into Staff (Name ,Department) values ('Fiona.Q.Fu' ,'WWW&BigData Tester');

-- SSL Tester
insert into Staff (Name ,Department) values ('Demi.W.Huang' ,'SSL Tester');	
insert into Staff (Name ,Department) values ('Agnes.Y.Xu' ,'SSL Tester');	
insert into Staff (Name ,Department) values ('Anna.C.Liu' ,'SSL Tester');	
insert into Staff (Name ,Department) values ('Anne.L.Zou' ,'SSL Tester');	
insert into Staff (Name ,Department) values ('Cathy.Y.Cheng' ,'SSL Tester');	
insert into Staff (Name ,Department) values ('David.G.Wu' ,'SSL Tester');	
insert into Staff (Name ,Department) values ('Monica.J.Tang' ,'SSL Tester');	
insert into Staff (Name ,Department) values ('Peter.P.Cai' ,'SSL Tester');	
insert into Staff (Name ,Department) values ('Nina.C.Fan' ,'SSL Tester');	

-- Special Tester
insert into Staff (Name ,Department) values ('Jennie.Z.Jian' ,'Special Tester');	
insert into Staff (Name ,Department) values ('Stuart.S.Hua' ,'Special Tester');	

-- Project
insert into ProjectInfo (LO,ProjectID,MISStatus,StartDate,ReleaseDate,DelayReleaseDate,LanuchDate,DelayLanuchDate) values(1,	13126,'Release','20160525',	'20160607',  '20160614',	'20160610' ,'20160617');
insert into ProjectInfo (LO,ProjectID,MISStatus,StartDate,ReleaseDate,DelayReleaseDate,LanuchDate,DelayLanuchDate) values(-1,	13129,'Load',   '20160526',	'20160610',  ''	       , '20160611' ,'20160615');	
insert into ProjectInfo (LO,ProjectID,MISStatus,StartDate,ReleaseDate,DelayReleaseDate,LanuchDate,DelayLanuchDate) values(2,	13167,'Coding', '20160614',	'20160705',  ''        ,  '20160708',  '');
insert into ProjectInfo (LO,ProjectID,MISStatus,StartDate,ReleaseDate,DelayReleaseDate,LanuchDate,DelayLanuchDate) values(3,	13166,'Coding', '20160614',	'20160706',  ''        ,  '20160711',  '');
insert into ProjectInfo (LO,ProjectID,MISStatus,StartDate,ReleaseDate,DelayReleaseDate,LanuchDate,DelayLanuchDate) values(4,	13133,'Coding', '20160526',	'20160720',  ''        ,  '20160729',  '');
insert into ProjectInfo (LO,ProjectID,MISStatus,StartDate,ReleaseDate,DelayReleaseDate,LanuchDate,DelayLanuchDate) values(-1,	13156,'Coding', '20160608',	'20160622',  ''        ,  '20160624',  '');
					
--  PB''
insert into PBInfo (PBNo , PBName) values ('BSAPT-3034','Update Volume Discount presentation and buy box logic.');
insert into PBInfo (PBNo , PBName) values ('COBRA-7', 'Item Service Improvement');
-----------------------------------------------------------------------------------------------------------------');
insert into PBInfo (PBNo , PBName) values ('SHECCP-14650','Accept USPS PO BOX in shipping address - EC'); 
insert into PBInfo (PBNo , PBName) values ('SHECCP-9206' ,'PayPal Unconfirmed Address - EC');
insert into PBInfo (PBNo , PBName) values ('SHECCP-14830' ,'Amex Card Distribution - record success application data');
insert into PBInfo (PBNo , PBName) values ('SHECCP-14807' ,'MasterPass Update');
insert into PBInfo (PBNo , PBName) values ('SHECCP-13390' ,'Product List 2016');
insert into PBInfo (PBNo , PBName) values ('ECSOLR-2814' ,'Replace get Lowest Price data from Hbase');
insert into PBInfo (PBNo , PBName) values ('ECSOLR-2815' ,'Replace Useful link data to Hbase');
insert into PBInfo (PBNo , PBName) values ('ECSOLR-2816' ,'Research the solution of get property data from Hbase');
insert into PBInfo (PBNo , PBName) values ('ECSOLR-2817' ,'integrate property value priority to jss');
insert into PBInfo (PBNo , PBName) values ('ECSOLR-2818' ,'Refactor Eyas UI');
----------------------------------------------------------- ,'------------------------------------------------------');
insert into PBInfo (PBNo , PBName) values ('SHECCP-13227','BOM Upsell (Other Buying Options)');
insert into PBInfo (PBNo , PBName) values ('SHECCP-12879','Send trace info by email');
insert into PBInfo (PBNo , PBName) values ('SHECCP-13675','In-house Scene7 style image functions');
insert into PBInfo (PBNo , PBName) values ('SHECCP-14313','EC - Warranty Information Display - Product Page Improvement');
insert into PBInfo (PBNo , PBName) values ('SHECCP-14826','Buzz review by parentitem');
insert into PBInfo (PBNo , PBName) values ('SHECCP-12589','To support for displaying "Customer Ratings" filter on Power Search page');
insert into PBInfo (PBNo , PBName) values ('SHECCP-4765' ,'create special promotion stores on demand');
insert into PBInfo (PBNo , PBName) values ('SHECCP-13564','Turnto upgrade version to 4.2');
insert into PBInfo (PBNo , PBName) values ('SHECCP-14597','Premier Relocation on site headers');
insert into PBInfo (PBNo , PBName) values ('SHECCP-11069','Add Premier Icon in Student Store');
insert into PBInfo (PBNo , PBName) values ('SHECYG-1029 ','complete missing compute fields logic');
insert into PBInfo (PBNo , PBName) values ('SHECYG-1028 ','Build up search biz ,data checking & analyzer system project');
insert into PBInfo (PBNo , PBName) values ('BSAPT-2778' ,'Ground Service Switch');
insert into PBInfo (PBNo , PBName) values ('BSAPT-2837' ,'Promo Code Adding Marketplace Item for Corporate(Marketing) Funded Promotions'); 
insert into PBInfo (PBNo , PBName) values ('BSAPT-2990' ,'Postback Solution'); 
insert into PBInfo (PBNo , PBName) values ('SHECCP-13612' ,'API for Extending Premier Membership'); 
insert into PBInfo (PBNo , PBName) values ('SHECCP-9111' ,'fix redeem eggpoint bug when split order'); 
insert into PBInfo (PBNo , PBName) values ('SHECCP-14502' ,'Update Promo code logic under shopping cart page');
insert into PBInfo (PBNo , PBName) values ('BSAPT-2941' ,'Hold at FedEx Location - EC'); 
--------------------------------------------------------- ,'--------------------------------------------------------');
insert into PBInfo (PBNo , PBName) values ('SHECCP-14531' ,'[Fix] PCode Remove Check SameDayMark Logic');
insert into PBInfo (PBNo , PBName) values ('SHECCP-13276' ,'Display Ship by Newegg for SBN item'); 
insert into PBInfo (PBNo , PBName) values ('SHECCP-13277' ,'Split order for SBN items');
insert into PBInfo (PBNo , PBName) values ('SHECCP-13278' ,'CAN SBN order features'); 
insert into PBInfo (PBNo , PBName) values ('SHECCP-14531' ,'Credit card reinput after shipping address change');
insert into PBInfo (PBNo , PBName) values ('SHECCP-13598' ,'Remove Email Check for Guest Checkout'); 
insert into PBInfo (PBNo , PBName) values ('SHECCP-14385' ,'Selling Used Items - Product List and Store');
insert into PBInfo (PBNo , PBName) values ('MKTPO-507' ,'Seller Profile Updates for Used Item');
insert into PBInfo (PBNo , PBName) values ('ECXAN-4364' ,'Update Purolator tracking API service');
insert into PBInfo (PBNo , PBName) values ('ECSOLR-2780' ,'Production testing Solrcloud for stability');
insert into PBInfo (PBNo , PBName) values ('ECSOLR-2781' ,'Immigrate JRJA to LevelDB Phase III');
insert into PBInfo (PBNo , PBName) values ('ECSOLR-2782' ,'Research to import properties , useful link data from hbase');
insert into PBInfo (PBNo , PBName) values ('ECSOLR-2783' ,'Implement get LowestPrice service for falcon consumer');
insert into PBInfo (PBNo , PBName) values ('ECSOLR-2784' ,'Research Redis-Cluster and compare with Redis master-slave');
insert into PBInfo (PBNo , PBName) values ('ECSOLR-2785' ,'Research Cloudera MapReduceTools Phase II');
insert into PBInfo (PBNo , PBName) values ('ECSOLR-2786' ,'create stemming dic for redirect link instance');
insert into PBInfo (PBNo , PBName) values ('SHECYG-1171' ,'AutoPart Solr HBase2Solr API upgrade CDH540');
-----------------------------------------------------------------------------------------------------------------
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(20, 100, 100, 'Domain Leader','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(21, 100, 100, '13127','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(22, 100, 100, '13127','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(23, 100, 100, '13133','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(24, 100, 100, '13133','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(25, 100, 100, '13126/13133','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(26, 100, 100, '13127','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(27, 100, 100, '13133','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(28, 100, 100, '13133','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(29, 100, 100, '13127','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(30, 100, 100, 'Domain Leader','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(31, 100, 100, '12783','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(32, 100, 100, '12783','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(33, 100, 100, '12783','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(34, 100, 100, '12783','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(35, 100, 100, 'Study','12/22 join team');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(36, 100, 100, '12779','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(37, 100, 100, '13084','12/1 join team');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(38, 100, 100, '13064','12/29 join team');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(39, 100, 100, 'Study','05/17 join team,undergraduate');																															
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(40, 100, 100, 'NULL','7/15 join team');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(41, 100, 100, 'Domain Leader','BA');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(42, 100, 100, 'NULl','7/8 Join Team');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(43, 100, 100, 'NULl','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(44, 100, 100, 'NULl','4/15 Join team');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(45, 100, 100, 'NULl','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(46, 100, 100, 'NULl','4/10 Join team');		 																																										
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(47, 100, 100, 'NULl','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(48, 100, 100, 'NULl','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(49, 100, 100, 'NULl','3/1/2016 Join team');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(50, 100, 100, '12877 bug fix','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(51, 100, 100, 'Domain Leader','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(52, 100, 100, '13127','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(53, 100, 100, 'performance tool','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(54, 100, 100, '13126','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(55, 100, 100, '13133','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(56, 100, 100, '13127','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(57, 100, 100, '13127','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(58, 100, 100, '13133','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(59, 100, 100, '13126','5/3/2016 join team');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(60, 100, 100, 'Domain Leader','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(61, 100, 100, 'NULL','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(62, 100, 100, 'NULL','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(63, 100, 100, 'NULL','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(64, 100, 100, 'NULL','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(65, 100, 100, 'NULL','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(66, 100, 100, 'NULL','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(67, 100, 100, 'NULL','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(68, 100, 100, 'study','4/12 join team');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(69, 100, 100, 'Domain Leader','NULL');																																												
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(70, 100, 100, 'BA','NULL');
insert into Domain (StaffId,Percentage,WorkLoadPercentage,Project,Memo) values(71, 100, 100, 'Team Leader','NULL');

-------------------------------------------------------------------------------------------------------------------------

/*
WorkType:
    0 --- Project
    1 -- Surpport
    2 --- 请假
    3 --- Arch
*/

insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (72,	'20160517', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (73,	'20160517', 0, 'Remove Email Check for Guest Checkout');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (46,	'20160517', 0, 'Credit card reinput after shipping address change');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (42,	'20160517', 0, 'Credit card reinput after shipping address change');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (44,	'20160517', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (43,	'20160517', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (45,	'20160517', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (47,	'20160517', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (40,	'20160517', 0, 'Remove Email Check for Guest Checkout');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (49,	'20160517', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (25,	'20160517', 0, 'Product page(lazy load)');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (28,	'20160517', 0, 'Product page(lazy load)');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (23,	'20160517', 0, 'Product page(lazy load)');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (27,	'20160517', 0, 'Product page(lazy load)');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (24,	'20160517', 0, 'Product page(lazy load)');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (21,	'20160517', 0, 'Product page(lazy load)');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (22,	'20160517', 0, 'Product page(lazy load)');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (29,	'20160517', 0, 'Product page(lazy load)');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (26,	'20160517', 0, 'Product page(lazy load)');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (72,	'20160524', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (73,	'20160524', 0, 'Remove Email Check for Guest Checkout');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (46,	'20160524', 0, 'Credit card reinput after shipping address change');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (42,	'20160524', 0, 'Credit card reinput after shipping address change');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (44,	'20160524', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (43,	'20160524', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (45,	'20160524', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (47,	'20160524', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (40,	'20160524', 0, 'Remove Email Check for Guest Checkout');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (49,	'20160524', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (25,	'20160524', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (28,	'20160524', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (23,	'20160524', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (27,	'20160524', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (24,	'20160524', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (21,	'20160524', 0, 'Selling Used Items - Product List and Store');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (22,	'20160524', 0, 'Selling Used Items - Product List and Store');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (29,	'20160524', 0, 'Selling Used Items - Product List and Store');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (26,	'20160524', 0, 'Selling Used Items - Product List and Store');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (72,	'20160531', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (73,	'20160531', 0, 'Remove Email Check for Guest Checkout');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (46,	'20160531', 0, 'Credit card reinput after shipping address change');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (42,	'20160531', 0, 'Credit card reinput after shipping address change');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (44,	'20160531', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (43,	'20160531', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (45,	'20160531', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (47,	'20160531', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (40,	'20160531', 0, 'Remove Email Check for Guest Checkout');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (49,	'20160531', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (25,	'20160531', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (28,	'20160531', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (23,	'20160531', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (27,	'20160531', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (24,	'20160531', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (21,	'20160531', 0, 'Selling Used Items - Product List and Store');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (22,	'20160531', 0, 'Selling Used Items - Product List and Store');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (29,	'20160531', 0, 'Selling Used Items - Product List and Store');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (26,	'20160531', 0, 'Selling Used Items - Product List and Store');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (72,	'20160607', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (73,	'20160607', 0, 'Remove Email Check for Guest Checkout');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (46,	'20160607', 0, 'Credit card reinput after shipping address change');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (42,	'20160607', 2, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (44,	'20160607', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (43,	'20160607', 0, 'CAN MKPL SBN');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (45,	'20160607', 2, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (47,	'20160607', 2, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (40,	'20160607', 0, 'Remove Email Check for Guest Checkout');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (49,	'20160607', 0, 'Pcode- APP');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (25,	'20160607', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (28,	'20160607', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (23,	'20160607', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (27,	'20160607', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (24,	'20160607', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (21,	'20160607', 0, 'Selling Used Items - Product List and Store');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (22,	'20160607', 0, 'Selling Used Items - Product List and Store');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (29,	'20160607', 0, 'Selling Used Items - Product List and Store');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (26,	'20160607', 0, 'Selling Used Items - Product List and Store');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (72,	'20160614', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (73,	'20160614', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (46,	'20160614', 0, 'Master Pass Upgrade');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (42,	'20160614', 0, 'Master Pass Upgrade');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (44,	'20160614', 0, 'Open PO Box OPTION');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (43,	'20160614', 0, 'Open PO Box OPTION');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (45,	'20160614', 0, 'Paypal unconfirmed address');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (47,	'20160614', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (40,	'20160614', 0, 'Master Pass Upgrade');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (49,	'20160614', 0, 'Open PO Box OPTION');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (25,	'20160614', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (28,	'20160614', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (23,	'20160614', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (27,	'20160614', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (24,	'20160614', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (21,	'20160614', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (22,	'20160614', 0, 'Turnto upgrade version to 4.2');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (29,	'20160614', 0, 'Turnto upgrade version to 4.2');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (26,	'20160614', 0, 'Turnto upgrade version to 4.2');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (72,	'20160621', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (73,	'20160621', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (46,	'20160621', 0, 'Master Pass Upgrade');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (42,	'20160621', 0, 'Master Pass Upgrade');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (44,	'20160621', 0, 'Open PO Box OPTION');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (43,	'20160621', 0, 'Open PO Box OPTION');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (45,	'20160621', 0, 'Paypal unconfirmed address');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (47,	'20160621', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (40,	'20160621', 0, 'Master Pass Upgrade');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (49,	'20160621', 0, 'Open PO Box OPTION');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (25,	'20160621', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (28,	'20160621', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (23,	'20160621', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (27,	'20160621', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (24,	'20160621', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (21,	'20160621', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (22,	'20160621', 0, 'Turnto upgrade version to 4.2');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (29,	'20160621', 0, 'Turnto upgrade version to 4.2');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (26,	'20160621', 0, 'Turnto upgrade version to 4.2');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (72,	'20160628', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (73,	'20160628', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (46,	'20160628', 0, 'Master Pass Upgrade');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (42,	'20160628', 0, 'Master Pass Upgrade');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (44,	'20160628', 0, 'Open PO Box OPTION');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (43,	'20160628', 0, 'Open PO Box OPTION');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (45,	'20160628', 0, 'Paypal unconfirmed address');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (47,	'20160628', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (40,	'20160628', 0, 'Master Pass Upgrade');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (49,	'20160628', 0, 'Open PO Box OPTION');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (25,	'20160628', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (28,	'20160628', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (23,	'20160628', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (27,	'20160628', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (24,	'20160628', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (21,	'20160628', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (22,	'20160628', 0, 'Turnto upgrade version to 4.2');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (29,	'20160628', 0, 'Turnto upgrade version to 4.2');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (26,	'20160628', 0, 'Turnto upgrade version to 4.2');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (72,	'20160705', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (73,	'20160705', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (46,	'20160705', 0, 'Master Pass Upgrade');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (42,	'20160705', 0, 'Master Pass Upgrade');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (44,	'20160705', 0, 'Open PO Box OPTION');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (43,	'20160705', 0, 'Open PO Box OPTION');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (45,	'20160705', 0, 'Paypal unconfirmed address');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (47,	'20160705', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (40,	'20160705', 0, 'Master Pass Upgrade');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (49,	'20160705', 0, 'Open PO Box OPTION');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (25,	'20160705', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (28,	'20160705', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (23,	'20160705', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (27,	'20160705', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (24,	'20160705', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (21,	'20160705', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (22,	'20160705', 0, 'In-house Scene7 style image functions');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (29,	'20160705', 0, 'In-house Scene7 style image functions');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (26,	'20160705', 0, 'In-house Scene7 style image functions');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (72,	'20160712', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (73,	'20160712', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (46,	'20160712', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (42,	'20160712', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (44,	'20160712', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (43,	'20160712', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (45,	'20160712', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (47,	'20160712', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (40,	'20160712', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (49,	'20160712', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (25,	'20160712', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (28,	'20160712', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (23,	'20160712', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (27,	'20160712', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (24,	'20160712', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (21,	'20160712', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (22,	'20160712', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (29,	'20160712', 0, 'In-house Scene7 style image functions');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (26,	'20160712', 0, 'In-house Scene7 style image functions');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (72,	'20160719', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (73,	'20160719', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (46,	'20160719', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (42,	'20160719', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (44,	'20160719', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (43,	'20160719', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (45,	'20160719', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (47,	'20160719', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (40,	'20160719', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (49,	'20160719', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (25,	'20160719', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (28,	'20160719', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (23,	'20160719', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (27,	'20160719', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (24,	'20160719', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (21,	'20160719', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (22,	'20160719', 0, 'In-house Scene7 style image functions');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (29,	'20160719', 0, 'In-house Scene7 style image functions');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (26,	'20160719', 0, 'In-house Scene7 style image functions');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (72,	'20160726', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (73,	'20160726', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (46,	'20160726', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (42,	'20160726', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (44,	'20160726', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (43,	'20160726', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (45,	'20160726', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (47,	'20160726', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (40,	'20160726', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (49,	'20160726', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (25,	'20160726', 1, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (28,	'20160726', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (23,	'20160726', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (27,	'20160726', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (24,	'20160726', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (21,	'20160726', 0, 'Product List 2016');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (22,	'20160726', 0, 'In-house Scene7 style image functions');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (29,	'20160726', 0, 'In-house Scene7 style image functions');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (26,	'20160726', 0, 'In-house Scene7 style image functions');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (72,	'20160802', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (73,	'20160802', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (46,	'20160802', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (42,	'20160802', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (44,	'20160802', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (43,	'20160802', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (45,	'20160802', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (47,	'20160802', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (40,	'20160802', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (49,	'20160802', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (25,	'20160802', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (28,	'20160802', 0, 'Premier Relocation on site headers');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (23,	'20160802', 0, 'Premier Relocation on site headers');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (27,	'20160802', 0, 'Premier Relocation on site headers');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (24,	'20160802', 0, 'Premier Relocation on site headers');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (21,	'20160802', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (22,	'20160802', 0, 'In-house Scene7 style image functions');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (29,	'20160802', 0, 'In-house Scene7 style image functions');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (26,	'20160802', 0, 'In-house Scene7 style image functions');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (72,	'20160809', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (73,	'20160809', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (46,	'20160809', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (42,	'20160809', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (44,	'20160809', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (43,	'20160809', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (45,	'20160809', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (47,	'20160809', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (40,	'20160809', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (49,	'20160809', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (25,	'20160809', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (28,	'20160809', 0, 'Premier Relocation on site headers');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (23,	'20160809', 0, 'Premier Relocation on site headers');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (27,	'20160809', 0, 'Premier Relocation on site headers');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (24,	'20160809', 0, 'Premier Relocation on site headers');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (21,	'20160809', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (22,	'20160809', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (29,	'20160809', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (26,	'20160809', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (72,	'20160816', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (73,	'20160816', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (46,	'20160816', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (42,	'20160816', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (44,	'20160816', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (43,	'20160816', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (45,	'20160816', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (47,	'20160816', 0, 'Refact Item Match Service');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (40,	'20160816', 0, 'Hold at FedEx Location');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (49,	'20160816', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (25,	'20160816', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (28,	'20160816', 0, 'Premier Relocation on site headers');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (23,	'20160816', 0, 'Premier Relocation on site headers');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (27,	'20160816', 0, 'Premier Relocation on site headers');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (24,	'20160816', 0, 'Premier Relocation on site headers');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (21,	'20160816', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (22,	'20160816', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (29,	'20160816', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (26,	'20160816', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (72,	'20160823', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (73,	'20160823', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (46,	'20160823', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (42,	'20160823', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (44,	'20160823', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (43,	'20160823', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (45,	'20160823', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (47,	'20160823', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (40,	'20160823', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (49,	'20160823', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (25,	'20160823', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (28,	'20160823', 0, 'Premier Relocation on site headers');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (23,	'20160823', 0, 'Premier Relocation on site headers');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (27,	'20160823', 0, 'Premier Relocation on site headers');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (24,	'20160823', 0, 'Premier Relocation on site headers');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (21,	'20160823', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (22,	'20160823', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (29,	'20160823', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (26,	'20160823', 0, 'NULL');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (50,	'20160517', 3, 'Arch');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (50,	'20160524', 3, 'Arch');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (50,	'20160531', 3, 'Arch');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (50,	'20160607', 3, 'Arch');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (50,	'20160614', 3, 'Arch');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (50,	'20160621', 3, 'Arch');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (50,	'20160628', 3, 'Arch');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (50,	'20160705', 3, 'Arch');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (50,	'20160712', 3, 'Arch');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (50,	'20160719', 3, 'Arch');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (50,	'20160726', 3, 'Arch');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (50,	'20160802', 3, 'Arch');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (50,	'20160809', 3, 'Arch');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (50,	'20160816', 3, 'Arch');
insert into WorkHours (StaffId, StartDate, WorkType, WorkContent) values (50,	'20160823', 3, 'Arch');